[package]
name = "@example/client-a"
type = "@apollo/operations"
description = "Client A"

[repository]
url = "https://github.com/lennyburdette/apm-example.git"
ref = "main"
path = "packages/client-a"

[registry]
url = "http://localhost:5150"

[dependencies]
"@example/public" = { tag = "dev" }
