name: Check Dependents

on:
  pull_request:
    branches:
      - main

jobs:
  check-dependents:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - client-a
          - posts
          - public
          - supergraph
          - users
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ORAS
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz
          tar -xzf oras_1.1.0_linux_amd64.tar.gz
          sudo mv oras /usr/local/bin/
          oras version

      - name: Get APM CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin
          mkdir -p ./bin
          oras pull ghcr.io/${{ github.repository_owner }}/apm:latest -o ./bin
          chmod +x ./bin/apm
          ./bin/apm --version

      - name: Check dependents for ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: ../../bin/apm check-dependents --tag dev
