name: Check Dependents

on:
  pull_request:
    branches:
      - main

jobs:
  check-dependents:
    runs-on: macos-latest
    strategy:
      matrix:
        package:
          - client-a
          - posts
          - public
          - supergraph
          - users
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes in ${{ matrix.package }}
        id: check_changes
        run: |
          if git diff --quiet origin/${{ github.base_ref }}...HEAD -- packages/${{ matrix.package }}; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Install ORAS
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          VERSION="1.3.0"
          ARCH="darwin_amd64"
          curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_${ARCH}.tar.gz"
          tar -xzf "oras_${VERSION}_${ARCH}.tar.gz"
          sudo mv oras /usr/local/bin/
          oras version

      - name: Get APM CLI
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin
          mkdir -p ./tmp
          oras pull ghcr.io/${{ github.repository_owner }}/apm:latest -o ./tmp
          mv ./tmp/target/release/apm ./apm
          chmod +x ./apm
          ./apm --help

      - name: Install Rover CLI
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Check dependents for ${{ matrix.package }}
        if: steps.check_changes.outputs.changed == 'true'
        working-directory: packages/${{ matrix.package }}
        env:
          APOLLO_ELV2_LICENSE: accept
        run: ../../apm check-dependents --tag dev --for-tag dev
