name: Check Dependents

on:
  pull_request:
    branches:
      - main

jobs:
  check-dependents:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - client-a
          - posts
          - public
          - supergraph
          - users
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ORAS
        run: |
          VERSION="1.1.0"
          ARCH="linux_amd64"
          curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_${ARCH}.tar.gz"
          tar -xzf "oras_${VERSION}_${ARCH}.tar.gz"
          sudo mv oras /usr/local/bin/
          oras version

      - name: Get APM CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin
          mkdir -p ./tmp
          oras pull ghcr.io/${{ github.repository_owner }}/apm:latest -o ./tmp
          mv ./tmp/target/release/apm ./apm
          chmod +x ./apm
          ./apm --version

      - name: Check dependents for ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: ../../apm check-dependents --tag dev
